spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/coffee_shop_db
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
server:
  port: 8081
